version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/medic_db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
